import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navigation from "@/components/Navigation";
import DarkModeToggle from "@/components/DarkModeToggle";
import { ThemeContextProvider } from "@/contexts/ThemeContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-200 relative`}
      >
        <ThemeContextProvider>
          <div className='backdrop-blur-md sticky top-0 transition-colors duration-200'>
            <div className='flex justify-between items-center max-w-4xl mx-auto'>
              <DarkModeToggle />
              <Navigation />
            </div>
          </div>
          <div className='max-w-2xl mx-auto'>
            {children}
          </div>
        </ThemeContextProvider>
      </body>
    </html>
  );
}